[package]
name = "mic_db_fill"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glob = "0.3.2"
hdf5 = "0.8.1"
image = "0.25.5"
ndarray = "0.15.6"
postgres = "0.19.10"
walkdir = "2.5.0"
